# Lab 2

## 23rd February 2021

### Q1
#### Create an array of dimension 5 x 4 x 3 using any two different ways. Comment the difference in the commands used.

In [4]:
# method 1
vector1 <- c(1,2,3,4,5)
vector2 <- c(1,2,3,4)
vector3 <- c(1,2,3)
array1 <- array(c(vector1,vector2,vector3),dim = c(5,4,3))
print(array1)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    1    2    4
[2,]    2    2    3    5
[3,]    3    3    1    1
[4,]    4    4    2    2
[5,]    5    1    3    3

, , 2

     [,1] [,2] [,3] [,4]
[1,]    4    2    2    3
[2,]    1    3    3    1
[3,]    2    4    4    2
[4,]    3    5    1    3
[5,]    1    1    2    4

, , 3

     [,1] [,2] [,3] [,4]
[1,]    5    1    3    3
[2,]    1    2    4    4
[3,]    2    3    5    1
[4,]    3    1    1    2
[5,]    4    2    2    3



In [16]:
array2<-c(1:60)
dim(array2)<-c(5,4,3)
print(array2)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    6   11   16
[2,]    2    7   12   17
[3,]    3    8   13   18
[4,]    4    9   14   19
[5,]    5   10   15   20

, , 2

     [,1] [,2] [,3] [,4]
[1,]   21   26   31   36
[2,]   22   27   32   37
[3,]   23   28   33   38
[4,]   24   29   34   39
[5,]   25   30   35   40

, , 3

     [,1] [,2] [,3] [,4]
[1,]   41   46   51   56
[2,]   42   47   52   57
[3,]   43   48   53   58
[4,]   44   49   54   59
[5,]   45   50   55   60



### Difference:

In the first part, ```array1 <- array(c(vector1,vector2,vector3),dim = c(5,4,3))``` , we are combining three vectors and giving dimensions, *at the time of the its creation*.

Whereas in the second part, we first create a vector ```array2<-c(1:60)``` and explicitly change its dimension ```dim(array2)<-c(5,4,3)```, without using the ```array()``` function.

### Q2
#### Create an array with 4 matrices of the dimension 6 x 6 using vector of any user defined sequence.

In [56]:
data <- c(1,2,3,4,5,6)
m1 <- matrix(data, nrow=6, ncol=6, byrow=TRUE)

data <- data+1
m2 <- matrix(data, nrow=6, ncol=6, byrow=TRUE)

data <- data+1
m3 <- matrix(data, nrow=6, ncol=6, byrow=TRUE)

data <- data+1
m4 <- matrix(data, nrow=6, ncol=6, byrow=TRUE)

array3 <- array(c(m1,m2,m3,m4),dim=c(4,6,6))

In [57]:
print(array3)

, , 1

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    1    2    3    3    4
[2,]    1    1    2    3    3    4
[3,]    1    2    2    3    4    4
[4,]    1    2    2    3    4    4

, , 2

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    5    5    6    2    2    3
[2,]    5    5    6    2    2    3
[3,]    5    6    6    2    3    3
[4,]    5    6    6    2    3    3

, , 3

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    4    4    5    6    6    7
[2,]    4    4    5    6    6    7
[3,]    4    5    5    6    7    7
[4,]    4    5    5    6    7    7

, , 4

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    3    3    4    5    5    6
[2,]    3    3    4    5    5    6
[3,]    3    4    4    5    6    6
[4,]    3    4    4    5    6    6

, , 5

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    7    7    8    4    4    5
[2,]    7    7    8    4    4    5
[3,]    7    8    8    4    5    5
[4,]    7    8    8    4    5    5

, , 6

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    6    6    7    8    8    9
[2,]    

### Q3
#### Convert 6 x 6 matrix into a one dimensional array.

In [35]:
array4 <- array(as.vector(m1)) #by columns
array5 <- array(as.vector(t(m2)))#by rows

In [41]:
cat("Class of array 4 -> ",class(array4))
cat("\n")
cat("Class of array 5 ->",class(array5))

Class of array 4 ->  array
Class of array 5 -> array

### Q4
#### Write a R program to create an array of two 6 x 4 matrices each with 6 rows and 4 columns from two given vectors. Print the second row of the second matrix of the array and the element in the 3rd row and 3rd column of the 1st matrix.

In [46]:
#values
data <- 1:24

#names
row_name <- c("row1", "row2", "row3", "row4","row5","row6") 
col_name <- c("col1", "col2", "col3", "col4") 

#putting together
m <- matrix(data, nrow = 6, dimnames = list(row_name, col_name))
data <- data*2
n <- matrix(data, nrow = 6, dimnames = list(row_name, col_name))

In [58]:
array6 <- array(c(m,n),dim<-c(4,6,2))

In [64]:
#second row of the second matrix 
print(array6[,,2][2,])

[1]  4 12 20 28 36 44


In [66]:
# element in the 3rd row and 3rd column of the 1st matrix
print(array6[,,1][,3][3])

[1] 11


### Q5

###  a
#### Create a matrix with dimension 7 x 7

In [71]:
data <- 1:49
m <- matrix(data,nrow = 7)
print(m)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]    1    8   15   22   29   36   43
[2,]    2    9   16   23   30   37   44
[3,]    3   10   17   24   31   38   45
[4,]    4   11   18   25   32   39   46
[5,]    5   12   19   26   33   40   47
[6,]    6   13   20   27   34   41   48
[7,]    7   14   21   28   35   42   49


### b
#### Replace the values of the $4^{th}$ column with mean of column value.

In [74]:
m[,4] <- mean(m[,4])

In [76]:
print(m)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]    1    8   15   25   29   36   43
[2,]    2    9   16   25   30   37   44
[3,]    3   10   17   25   31   38   45
[4,]    4   11   18   25   32   39   46
[5,]    5   12   19   25   33   40   47
[6,]    6   13   20   25   34   41   48
[7,]    7   14   21   25   35   42   49


### c
#### Name the rows with a prefix “rownum”

In [77]:
rownames(m) <- c("rownum 1","rownum 2","rownum 3","rownum 4","rownum 5","rownum 6","rownum 7")

In [78]:
print(m)

         [,1] [,2] [,3] [,4] [,5] [,6] [,7]
rownum 1    1    8   15   25   29   36   43
rownum 2    2    9   16   25   30   37   44
rownum 3    3   10   17   25   31   38   45
rownum 4    4   11   18   25   32   39   46
rownum 5    5   12   19   25   33   40   47
rownum 6    6   13   20   25   34   41   48
rownum 7    7   14   21   25   35   42   49


### d
#### Use r command to name the columns with the vector sequence [level1, level2,level3……., level6, level7]

In [79]:
colnames(m) <- c("level1","level2","level3","level4","level5","level6","level7")

In [80]:
print(m)

         level1 level2 level3 level4 level5 level6 level7
rownum 1      1      8     15     25     29     36     43
rownum 2      2      9     16     25     30     37     44
rownum 3      3     10     17     25     31     38     45
rownum 4      4     11     18     25     32     39     46
rownum 5      5     12     19     25     33     40     47
rownum 6      6     13     20     25     34     41     48
rownum 7      7     14     21     25     35     42     49


### Q6
#### You are an assistant officer in an ecommerce warehouse. Your duty includes managing the inventory, stocking the products and doing the survey for the products and keep the record of the same. Recently you have been asked to come up with a way to manage and calculate few basic operations on the records. You have a basic knowledge in r. You need to create a dataset using arrays and show few basic operations on the same to provide a summary.

### a
#### Use poisson distribution to create a matrix of 100 elements for a 20 x 5 matrix with a mean of 48.5.

In [145]:
set.seed(42)
n <- 1:100
data <- rpois(n, lambda = 48.40)

In [146]:
mean(data)

[1] 48.51

In [147]:
m <- matrix(data,nrow=20,ncol=5)

In [148]:
print(m)

      [,1] [,2] [,3] [,4] [,5]
 [1,]   57   60   52   41   54
 [2,]   44   50   48   53   44
 [3,]   48   50   50   54   40
 [4,]   40   45   42   59   37
 [5,]   47   36   59   41   52
 [6,]   58   41   52   53   56
 [7,]   47   51   49   51   55
 [8,]   62   53   50   42   41
 [9,]   47   55   53   51   48
[10,]   57   44   49   49   43
[11,]   64   43   27   42   45
[12,]   38   42   55   47   55
[13,]   57   52   46   40   45
[14,]   55   46   52   46   48
[15,]   54   49   58   47   49
[16,]   51   45   43   54   45
[17,]   55   49   50   54   42
[18,]   42   39   59   58   45
[19,]   46   51   49   45   33
[20,]   61   42   40   53   38


### b
#### Use the column names as Week1, week2, week3, week4, week5.

In [149]:
colnames(m) <- c(" Week1", "Week2", "Week3", "Week4", "Week5")

In [150]:
print(m)

       Week1 Week2 Week3 Week4 Week5
 [1,]     57    60    52    41    54
 [2,]     44    50    48    53    44
 [3,]     48    50    50    54    40
 [4,]     40    45    42    59    37
 [5,]     47    36    59    41    52
 [6,]     58    41    52    53    56
 [7,]     47    51    49    51    55
 [8,]     62    53    50    42    41
 [9,]     47    55    53    51    48
[10,]     57    44    49    49    43
[11,]     64    43    27    42    45
[12,]     38    42    55    47    55
[13,]     57    52    46    40    45
[14,]     55    46    52    46    48
[15,]     54    49    58    47    49
[16,]     51    45    43    54    45
[17,]     55    49    50    54    42
[18,]     42    39    59    58    45
[19,]     46    51    49    45    33
[20,]     61    42    40    53    38


### c
#### Use r operation to create a new row with the average value of each column.

In [151]:
mean_col <- c(mean(m[,1]),mean(m[,2]),mean(m[,3]),mean(m[,4]),mean(m[,5])) 

In [152]:
m <- rbind(m, mean_col) 

In [153]:
print(m)

          Week1 Week2 Week3 Week4 Week5
           57.0 60.00 52.00    41 54.00
           44.0 50.00 48.00    53 44.00
           48.0 50.00 50.00    54 40.00
           40.0 45.00 42.00    59 37.00
           47.0 36.00 59.00    41 52.00
           58.0 41.00 52.00    53 56.00
           47.0 51.00 49.00    51 55.00
           62.0 53.00 50.00    42 41.00
           47.0 55.00 53.00    51 48.00
           57.0 44.00 49.00    49 43.00
           64.0 43.00 27.00    42 45.00
           38.0 42.00 55.00    47 55.00
           57.0 52.00 46.00    40 45.00
           55.0 46.00 52.00    46 48.00
           54.0 49.00 58.00    47 49.00
           51.0 45.00 43.00    54 45.00
           55.0 49.00 50.00    54 42.00
           42.0 39.00 59.00    58 45.00
           46.0 51.00 49.00    45 33.00
           61.0 42.00 40.00    53 38.00
mean_col   51.5 47.15 49.15    49 45.75


### d
#### Use r operation to create a new column with the average value of each row.

In [154]:
vec <- c()
for(i in 1:20)
{
    vec <- append(vec,mean(m[i,]))
}

m <- cbind(m, vec) 

Warning message in cbind(m, vec):
"number of rows of result is not a multiple of vector length (arg 2)"

In [155]:
print(m)

          Week1 Week2 Week3 Week4 Week5  vec
           57.0 60.00 52.00    41 54.00 52.8
           44.0 50.00 48.00    53 44.00 47.8
           48.0 50.00 50.00    54 40.00 48.4
           40.0 45.00 42.00    59 37.00 44.6
           47.0 36.00 59.00    41 52.00 47.0
           58.0 41.00 52.00    53 56.00 52.0
           47.0 51.00 49.00    51 55.00 50.6
           62.0 53.00 50.00    42 41.00 49.6
           47.0 55.00 53.00    51 48.00 50.8
           57.0 44.00 49.00    49 43.00 48.4
           64.0 43.00 27.00    42 45.00 44.2
           38.0 42.00 55.00    47 55.00 47.4
           57.0 52.00 46.00    40 45.00 48.0
           55.0 46.00 52.00    46 48.00 49.4
           54.0 49.00 58.00    47 49.00 51.4
           51.0 45.00 43.00    54 45.00 47.6
           55.0 49.00 50.00    54 42.00 50.0
           42.0 39.00 59.00    58 45.00 48.6
           46.0 51.00 49.00    45 33.00 44.8
           61.0 42.00 40.00    53 38.00 46.8
mean_col   51.5 47.15 49.15    49 45.75 52.8
